# Python stubs generated by omniidl from WordyApp.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


#
# Start of module "WordyApp"
#
__name__ = "WordyApp"
_0_WordyApp = omniORB.openModule("WordyApp", r"WordyApp.idl")
_0_WordyApp__POA = omniORB.openModule("WordyApp__POA", r"WordyApp.idl")


# typedef ... array
class array:
    _NP_RepositoryId = "IDL:WordyApp/array:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_WordyApp.array = array
_0_WordyApp._d_array  = (omniORB.tcInternal.tv_sequence, (omniORB.tcInternal.tv_string,0), 0)
_0_WordyApp._ad_array = (omniORB.tcInternal.tv_alias, array._NP_RepositoryId, "array", (omniORB.tcInternal.tv_sequence, (omniORB.tcInternal.tv_string,0), 0))
_0_WordyApp._tc_array = omniORB.tcInternal.createTypeCode(_0_WordyApp._ad_array)
omniORB.registerType(array._NP_RepositoryId, _0_WordyApp._ad_array, _0_WordyApp._tc_array)
del array

# interface WordyGame
_0_WordyApp._d_WordyGame = (omniORB.tcInternal.tv_objref, "IDL:WordyApp/WordyGame:1.0", "WordyGame")
omniORB.typeMapping["IDL:WordyApp/WordyGame:1.0"] = _0_WordyApp._d_WordyGame
_0_WordyApp.WordyGame = omniORB.newEmptyClass()
class WordyGame :
    _NP_RepositoryId = _0_WordyApp._d_WordyGame[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_WordyApp.WordyGame = WordyGame
_0_WordyApp._tc_WordyGame = omniORB.tcInternal.createTypeCode(_0_WordyApp._d_WordyGame)
omniORB.registerType(WordyGame._NP_RepositoryId, _0_WordyApp._d_WordyGame, _0_WordyApp._tc_WordyGame)

# WordyGame operations and attributes
WordyGame._d_login = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), ((omniORB.tcInternal.tv_string,0), ), None)
WordyGame._d_logout = (((omniORB.tcInternal.tv_string,0), ), (), None)
WordyGame._d_register = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), (omniORB.tcInternal.tv_boolean, ), None)
WordyGame._d_getUserIDFromUsername = (((omniORB.tcInternal.tv_string,0), ), (omniORB.tcInternal.tv_long, ), None)
WordyGame._d_getPlayerList = ((), (omniORB.typeMapping["IDL:WordyApp/array:1.0"], ), None)
WordyGame._d_getFiveLongestWords = ((), (omniORB.typeMapping["IDL:WordyApp/array:1.0"], ), None)
WordyGame._d_getTopFivePlayers = ((), (omniORB.typeMapping["IDL:WordyApp/array:1.0"], ), None)
WordyGame._d_getWordsData = ((), (omniORB.typeMapping["IDL:WordyApp/array:1.0"], ), None)
WordyGame._d_getRandomLetters = ((omniORB.tcInternal.tv_long, ), ((omniORB.tcInternal.tv_string,0), ), None)
WordyGame._d_validateInput = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0), omniORB.typeMapping["IDL:WordyApp/array:1.0"]), (omniORB.tcInternal.tv_boolean, ), None)
WordyGame._d_updateLongestWordFormed = ((omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), (), None)
WordyGame._d_insertIntoLeaderboardTable = ((omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_long), (), None)
WordyGame._d_setLongestWordToNull = (((omniORB.tcInternal.tv_string,0), ), (), None)
WordyGame._d_getLongestWordLength = ((omniORB.tcInternal.tv_long, ), (omniORB.tcInternal.tv_long, ), None)
WordyGame._d_compareWordFormedToLongestWord = ((omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0)), (), None)
WordyGame._d_checkPointsAchieved = (((omniORB.tcInternal.tv_string,0), ), (omniORB.tcInternal.tv_boolean, ), None)
WordyGame._d_checkExistingUserID = ((omniORB.tcInternal.tv_long, ), (omniORB.tcInternal.tv_boolean, ), None)
WordyGame._d_updateMatchesWon = ((omniORB.tcInternal.tv_long, ), (), None)
WordyGame._d_modifyPointsAchieved = ((omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0)), (omniORB.tcInternal.tv_long, ), None)
WordyGame._d_startNewWaitingRoom = ((), (), None)
WordyGame._d_joinWaitingRoom = (((omniORB.tcInternal.tv_string,0), ), (omniORB.tcInternal.tv_boolean, ), None)
WordyGame._d_leaveWaitingRoom = (((omniORB.tcInternal.tv_string,0), ), (), None)
WordyGame._d_checkWaitingRoomStatus = ((), (omniORB.typeMapping["IDL:WordyApp/array:1.0"], ), None)
WordyGame._d_displayScores = ((omniORB.tcInternal.tv_long, ), (omniORB.tcInternal.tv_long, ), None)
WordyGame._d_getPlayersInGameSession = (((omniORB.tcInternal.tv_string,0), ), (omniORB.typeMapping["IDL:WordyApp/array:1.0"], ), None)

# WordyGame object reference
class _objref_WordyGame (CORBA.Object):
    _NP_RepositoryId = WordyGame._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def login(self, *args):
        return self._obj.invoke("login", _0_WordyApp.WordyGame._d_login, args)

    def logout(self, *args):
        return self._obj.invoke("logout", _0_WordyApp.WordyGame._d_logout, args)

    def register(self, *args):
        return self._obj.invoke("register", _0_WordyApp.WordyGame._d_register, args)

    def getUserIDFromUsername(self, *args):
        return self._obj.invoke("getUserIDFromUsername", _0_WordyApp.WordyGame._d_getUserIDFromUsername, args)

    def getPlayerList(self, *args):
        return self._obj.invoke("getPlayerList", _0_WordyApp.WordyGame._d_getPlayerList, args)

    def getFiveLongestWords(self, *args):
        return self._obj.invoke("getFiveLongestWords", _0_WordyApp.WordyGame._d_getFiveLongestWords, args)

    def getTopFivePlayers(self, *args):
        return self._obj.invoke("getTopFivePlayers", _0_WordyApp.WordyGame._d_getTopFivePlayers, args)

    def getWordsData(self, *args):
        return self._obj.invoke("getWordsData", _0_WordyApp.WordyGame._d_getWordsData, args)

    def getRandomLetters(self, *args):
        return self._obj.invoke("getRandomLetters", _0_WordyApp.WordyGame._d_getRandomLetters, args)

    def validateInput(self, *args):
        return self._obj.invoke("validateInput", _0_WordyApp.WordyGame._d_validateInput, args)

    def updateLongestWordFormed(self, *args):
        return self._obj.invoke("updateLongestWordFormed", _0_WordyApp.WordyGame._d_updateLongestWordFormed, args)

    def insertIntoLeaderboardTable(self, *args):
        return self._obj.invoke("insertIntoLeaderboardTable", _0_WordyApp.WordyGame._d_insertIntoLeaderboardTable, args)

    def setLongestWordToNull(self, *args):
        return self._obj.invoke("setLongestWordToNull", _0_WordyApp.WordyGame._d_setLongestWordToNull, args)

    def getLongestWordLength(self, *args):
        return self._obj.invoke("getLongestWordLength", _0_WordyApp.WordyGame._d_getLongestWordLength, args)

    def compareWordFormedToLongestWord(self, *args):
        return self._obj.invoke("compareWordFormedToLongestWord", _0_WordyApp.WordyGame._d_compareWordFormedToLongestWord, args)

    def checkPointsAchieved(self, *args):
        return self._obj.invoke("checkPointsAchieved", _0_WordyApp.WordyGame._d_checkPointsAchieved, args)

    def checkExistingUserID(self, *args):
        return self._obj.invoke("checkExistingUserID", _0_WordyApp.WordyGame._d_checkExistingUserID, args)

    def updateMatchesWon(self, *args):
        return self._obj.invoke("updateMatchesWon", _0_WordyApp.WordyGame._d_updateMatchesWon, args)

    def modifyPointsAchieved(self, *args):
        return self._obj.invoke("modifyPointsAchieved", _0_WordyApp.WordyGame._d_modifyPointsAchieved, args)

    def startNewWaitingRoom(self, *args):
        return self._obj.invoke("startNewWaitingRoom", _0_WordyApp.WordyGame._d_startNewWaitingRoom, args)

    def joinWaitingRoom(self, *args):
        return self._obj.invoke("joinWaitingRoom", _0_WordyApp.WordyGame._d_joinWaitingRoom, args)

    def leaveWaitingRoom(self, *args):
        return self._obj.invoke("leaveWaitingRoom", _0_WordyApp.WordyGame._d_leaveWaitingRoom, args)

    def checkWaitingRoomStatus(self, *args):
        return self._obj.invoke("checkWaitingRoomStatus", _0_WordyApp.WordyGame._d_checkWaitingRoomStatus, args)

    def displayScores(self, *args):
        return self._obj.invoke("displayScores", _0_WordyApp.WordyGame._d_displayScores, args)

    def getPlayersInGameSession(self, *args):
        return self._obj.invoke("getPlayersInGameSession", _0_WordyApp.WordyGame._d_getPlayersInGameSession, args)

omniORB.registerObjref(WordyGame._NP_RepositoryId, _objref_WordyGame)
_0_WordyApp._objref_WordyGame = _objref_WordyGame
del WordyGame, _objref_WordyGame

# WordyGame skeleton
__name__ = "WordyApp__POA"
class WordyGame (PortableServer.Servant):
    _NP_RepositoryId = _0_WordyApp.WordyGame._NP_RepositoryId


    _omni_op_d = {"login": _0_WordyApp.WordyGame._d_login, "logout": _0_WordyApp.WordyGame._d_logout, "register": _0_WordyApp.WordyGame._d_register, "getUserIDFromUsername": _0_WordyApp.WordyGame._d_getUserIDFromUsername, "getPlayerList": _0_WordyApp.WordyGame._d_getPlayerList, "getFiveLongestWords": _0_WordyApp.WordyGame._d_getFiveLongestWords, "getTopFivePlayers": _0_WordyApp.WordyGame._d_getTopFivePlayers, "getWordsData": _0_WordyApp.WordyGame._d_getWordsData, "getRandomLetters": _0_WordyApp.WordyGame._d_getRandomLetters, "validateInput": _0_WordyApp.WordyGame._d_validateInput, "updateLongestWordFormed": _0_WordyApp.WordyGame._d_updateLongestWordFormed, "insertIntoLeaderboardTable": _0_WordyApp.WordyGame._d_insertIntoLeaderboardTable, "setLongestWordToNull": _0_WordyApp.WordyGame._d_setLongestWordToNull, "getLongestWordLength": _0_WordyApp.WordyGame._d_getLongestWordLength, "compareWordFormedToLongestWord": _0_WordyApp.WordyGame._d_compareWordFormedToLongestWord, "checkPointsAchieved": _0_WordyApp.WordyGame._d_checkPointsAchieved, "checkExistingUserID": _0_WordyApp.WordyGame._d_checkExistingUserID, "updateMatchesWon": _0_WordyApp.WordyGame._d_updateMatchesWon, "modifyPointsAchieved": _0_WordyApp.WordyGame._d_modifyPointsAchieved, "startNewWaitingRoom": _0_WordyApp.WordyGame._d_startNewWaitingRoom, "joinWaitingRoom": _0_WordyApp.WordyGame._d_joinWaitingRoom, "leaveWaitingRoom": _0_WordyApp.WordyGame._d_leaveWaitingRoom, "checkWaitingRoomStatus": _0_WordyApp.WordyGame._d_checkWaitingRoomStatus, "displayScores": _0_WordyApp.WordyGame._d_displayScores, "getPlayersInGameSession": _0_WordyApp.WordyGame._d_getPlayersInGameSession}

WordyGame._omni_skeleton = WordyGame
_0_WordyApp__POA.WordyGame = WordyGame
omniORB.registerSkeleton(WordyGame._NP_RepositoryId, WordyGame)
del WordyGame
__name__ = "WordyApp"

#
# End of module "WordyApp"
#
__name__ = "WordyApp_idl"

_exported_modules = ( "WordyApp", )

# The end.
